project:
  type: website
  output-dir: ../docs

website:
  title: "Butyrate, Microbiome and ICB Outcomes"
  navbar:
    left:
      - icon: github
        href: "https://github.com/mskcc-microbiome/butyrate_and_icb_2025" 
  sidebar:
    style: "floating"
    search: true
    collapse-level: 3
    contents: 
      - section: "Analysis Notes"
        contents: 
          - text: "shortBRED Analysis Butyrate Gene Quantification"
            href: shortbred_analysis_intro.qmd
          - text: "All Text HR values"
            href: all_text_hr_values.qmd
      - section: "Main Figures"
        contents: 
          - text: "Figure 1: Hazard Ratio with Fiber"
            href: figure_1.qmd
          - text: "Figure 2: ACoA Pathway and ICB/Survival Outcomes"
            href: figure_2.qmd
      - section: "Extended Figures"
        contents:  
          - text: "Extended Figure 1"
            href: extended_data_figure_1.qmd
          - text: "Extended Figure 2"
            href: extended_data_figure_2.qmd
          - text: "Extended Figure 3"
            href: extended_data_figure_3.qmd
          - text: "Extended Figure 4"
            href: extended_data_figure_4.qmd
          - text: "Extended Figure 5"
            href: extended_data_figure_5.qmd
          - text: "Extended Figure 6"
            href: extended_data_figure_6.qmd
          - text: "Extended Figure 7"
            href: extended_data_figure_7.qmd
          - text: "Extended Figure 8"
            href: extended_data_figure_8.qmd
          - text: "Extended Figure 9"
            href: extended_data_figure_9.qmd
      - section: "Tables"
        contents: 
          - text: "Extended Data Table 1"
            href: table_1.qmd
          - text: "Extended Data Table 2"
            href: table_2.qmd
          - text: "Extended Data Table 3"
            href: table_3.qmd
          - text: "Extended Data Table 4"
            href: table_4.qmd
          - text: "Extended Data Table 5"
            href: table_5.qmd
          - text: "Extended Data Table 6"
            href: table_6.qmd
          - text: "Extended Data Table 7"
            href: table_7.qmd
          - text: "Extended Data Table 8"
            href: table_8.qmd
          - text: "Extended Data Table 9"
            href: table_9.qmd
      - section: "Other Figures"
        contents: 
          - text: "External and Internal Cohort Multivariable Analysis"
            href: wargo_multivariate_figure.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    embed-resources: true



