--- 
title: |
  Extended Figure 1: PFS vs Fiber by Disease Type
---



```{r}
#| echo: false
#| warning: false
#| include: false
#| label: library_data_imports

library(dplyr)
library(survival)
library(stats)
library(survminer)
library(forestplot)
source("utility_funcs.R")
```

The data we are visualizing here has the following structure:


```{r}
#| warning: false
#| include: false
#| label: load_data


all_metadata_fiber <- readRDS("../public_data/fiber_data/all_metadata_fiber.RDS") %>%
  mutate(aofib = as.numeric(aofib)) %>%
  mutate(fiber_density = aofib/calor)%>%
  mutate(fiber_density_kcal = 1000*fiber_density)

```

```{r}
#| warning: false
#| include: false
#| label: raw_hist

median_fiber = median(all_metadata_fiber$aofib)

tertiles = quantile(all_metadata_fiber$aofib, probs = c(1/3, 2/3))

ggplot(all_metadata_fiber, aes(x = aofib)) +
  geom_histogram(binwidth = 2) +
  theme_minimal() +
  ylim(0, 50) +
  labs(
    title = "Raw grams of fiber distribution",
    x = "Grams of fiber",
    y = "Num Patients"
  ) +
  geom_vline(xintercept = 28, color = "red", size = 1) + 
  annotate("text", x = 28, y =20, label = "Nutritionist\nRecommendation(28)", color = "black", angle = 0, hjust = 1.1) +
  geom_vline(xintercept = 20, color = "red", size = 1) + 
  annotate("text", x = 20, y =42, label = "Spencer\nThreshold(20)", color = "black", angle = 0, hjust = 0) +
  geom_vline(xintercept = 50, color = "red", size = 1) + 
  annotate("text", x = 50, y =12, label = "Reviewer suggestion(50)", color = "black", angle = 0, hjust = 1.1) +
  geom_vline(xintercept = median_fiber, color = "steelblue", size = 1) + 
  annotate("text", x = median_fiber, y =30, label = paste0("Data Median (",median_fiber,")"), color = "black", angle = 90, vjust = -1) +
  geom_vline(xintercept = tertiles[1], color = "steelblue", size = 1) + 
  annotate("text", x = tertiles[1], y =30, label = paste0("Bottom Tertile (",tertiles[1],")"), color = "black", angle = 90, vjust = -1) +
  geom_vline(xintercept = tertiles[2], color = "steelblue", size = 1) + 
  annotate("text", x = tertiles[2], y =30, label = paste0("Top Tertile (",tertiles[2],")"), color = "black", angle = 90, vjust = -1) +  
  geom_vline(xintercept = 14.4, color = "red", size = 1) + 
  annotate("text", x = 14.4, y =45, label = "NHANES women (14.4)", color = "black", angle = 0, hjust = 1.1) +
  geom_vline(xintercept = 17.9, color = "red", size = 1) + 
  annotate("text", x = 17.9, y =40, label = "NHANES men (17.9)", color = "black", angle = 0, hjust = 1.1) +
  geom_vline(xintercept = 15, color = "red", size = 1) + 
  annotate("text", x = 15, y =15, label = "This\nManuscript\nThreshold (15)", color = "black", angle = 0, hjust = 1.1) 


save_figures("annotated_raw_fiber_distribution")

```

```{r}
#| warning: false
#| include: false
#| label: norm_hist

median_fiber = median(all_metadata_fiber$aofib)

median_calor = median(all_metadata_fiber$calor)
ggplot(all_metadata_fiber, aes(x = fiber_density_kcal)) +
  geom_histogram(num_bins = 30) +
  theme_minimal() +
  labs(
    title = "Fiber Density Distribution",
    x = "Grams of fiber/1000 Calories",
    y = "Num Patients"
  ) +
  geom_vline(xintercept = 15000/median_calor, color = "red", size = 1)

```

