--- 
title: |
  Extended Data Table  2
format:
  html:
    css: styles.css
---



```{r}
#| echo: false
#| warning: false
#| include: false
#| label: library_data_imports

library(tidyverse)
library(table1)
library(gtsummary)
library(yingtools2)
source("utility_funcs.R")
gu_cohort_data <- readRDS("../data/gu_survey_cohort.RDS")

```

```{r}
#| warning: false
#| include: true
#| echo: false
#| label: import_data_add_labels

gu_cohort_data %>% 
  mutate(above_below_label = ifelse(gram_fiber_per_Kcal_aboveRecommended == 0, "below 15g/1000 kcal", "above 15g/1000 kcal")) %>% 
  select(above_below_label,calor,
                                                            age,sex.factor,cancer_RCCvsUC_NAME,
                                                            race.factor,
                                                            latinx.factor,bmi,
                                                            ecog_kpsConverted,stage.simplified.factor,smoke.factor,
                                                            Impact.TMB.Score) %>% 
  tbl_summary(by = above_below_label) %>%
  modify_caption("**Supplementary Table. Baseline characteristics of all patients by fiber intake**")
```
