## Software paths:


## bbmap
adapters_fasta: "/data/brinkvd/resources/references/synthetic/stephenturner-adapters/93b5f91/adapters_combined_256_unique.fasta"
filter_params: "minlen=51 qtrim=rl trimq=10 ktrim=r k=31 mink=9 hdist=1 hdist2=1 tpe tbo"

## General Parameters
retries: 3

## bioBakery
choco_db: "/data/brinkvd/resources/dbs/chocophlan/v201901_v31/"
uniref90_db: "/data/brinkvd/resources/dbs/uniref90_diamond/v201901b/"
utility_mapping_db: "/data/brinkvd/resources/dbs/utility_mapping/utility_mapping/"
metaphlan_db: "/data/brinkvd/resources/dbs/metaphlan/mpa_vJan21_CHOCOPhlAnSGB_202103/"
skip_sample2markers: false

## CheckM
checkm_db: "/data/brinkvd/resources/dbs/checkm/2015_01_16/"