quantify_script: "(the path to the shortBRED quantify_script)"
marker_fastq: "(path to the marker fastq we provided (or updated marker.fastq if using your own reference))."
usearch: "the path to your usearch installation."