quantify_script: "/home/daia1/my_workdir/APPS/shortbred/shortbred_quantify.py"
marker_fastq: "/home/daia1/my_workdir/other_pipeline/butyrate_gene_quantify/data/butyrate_pw_genes_markers.fa"
usearch: "/home/daia1/my_workdir/APPS/usearch11.0.667_i86linux32"
